### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by TheFonix** [Taconut/Solder-Uploader#1]
So i have gone through and filled in all of the config but cant seem to get any joy out of this project, all i seem to end up with is a blank screen.

**Comment by Taconut** [comment]
Uh I made this like 5 million years ago; I don't even play this game anymore. It'd probably be easier to make this yourself in PHP or Node or something. This thing was made back when I had absolutely no idea how to code.

Sorry for the inconvenience and good luck in your endeavors.
